[[redirects]]
from = "/docs/reference/sql/backup/"
to = "/docs/reference/sql/snapshot/"

[[redirects]]
from = "/blog/2021/05/10/questdb-release-6-0-tsbs-benchmark/"
to = "/blog/building-a-new-vector-based-storage-model/"

[[redirects]]
from = "/blog/crypto-data-visualization-dashboards-grafana/"
to = "/blog/2022/04/12/demo-live-crypto-data-streamed-with-questdb-and-grafana/"

[[redirects]]
from = "/write-time/"
to = "/"

[[redirects]]
from = "/finance/"
to = "/market-data/"

[[redirects]]
from = "/docs/third-party-tools/data-bento/"
to = "/docs/third-party-tools/databento/"

[[redirects]]
from = "/community/"
to = "/contributors/"

[[redirects]]
from = "/docs/reference/api/ilp/authenticate/"
to = "/docs/reference/api/ilp/overview/"

[[redirects]]
from = "/docs/clients/ingest-cpp/"
to = "/docs/clients/ingest-c-and-cpp/"

[[redirects]]
from = "/docs/clients/ingest-c/"
to = "/docs/clients/ingest-c-and-cpp/"

[[redirects]]
from = "/blog/comparing-influxdb-timescaledb-questdb-time-series-databases/"
to = "/blog/timescaledb-vs-questdb-comparison/"

[[redirects]]
from = "/docs/reference/clients/overview/"
to = "/docs/ingestion-overview/"

[[redirects]]
from = "/docs/reference/clients/java_ilp"
to = "/docs/clients/java_ilp"

[[redirects]]
from = "/docs/ingestion-primer/"
to = "/docs/ingestion-overview/"

[[redirects]]
from = "/docs/reference/clients/*"
to = "/docs/clients/:splat"
status = 301
force = true

[[redirects]]
from = "/docs/reference/sql/acl/permissions/"
to = "/docs/operations/rbac/"

[[redirects]]
from = "/docs/reference/sql/acl/summary/"
to = "/docs/operations/rbac/"

[[redirects]]
from = "/glossary/tsdb/"
to = "/glossary/time-series-database/"

[[redirects]]
from = "/docs/reference/api/ilp/authentication/"
to = "/docs/reference/api/ilp/overview/#authentication"

[[redirects]]
from = "/docs/reference/api/ilp/tcp-receiver/"
to = "/docs/reference/api/ilp/overview/"

[[redirects]]
from = "/docs/reference/api/ilp/udp-receiver/"
to = "/docs/reference/api/ilp/overview/"


[[redirects]]
from = "/docs/guides/v6-migration/"
to = "/docs/"

[[redirects]]
from = "/blog/2021/11/29/questdb-versus-influxdb/"
to = "/blog/2024/02/26/questdb-versus-influxdb/"

[[redirects]]
from = "/docs/guides/importing-data/"
to = "/docs/guides/import-csv/"

[[redirects]]
from = "/blog/2021/08/18/questdb-versus-timescaledb/"
to = "/blog/comparing-influxdb-timescaledb-questdb-time-series-databases/"

[[redirects]]
from = "/getstarted"
to = "/"

[[redirects]]
from = "/docs/reference/operators/pattern-matching/"
to = "/docs/reference/function/pattern-matching/"

[[redirects]]
from = "/get-started"
to = "/"

[[redirects]]
from = "/docs/reference/web-console"
to = "/docs/web-console"

[[redirects]]
from = "/docs/develop/web-console/"
to = "/docs/web-console"

[[redirects]]
from = "/docs/first-database"
to = "/docs/guides/create-database/"

[[redirects]]
from = "/docs/develop/connect/"
to = "/docs/ingestion-overview"

[[redirects]]
from = "/docs/develop/insert/"
to = "/docs/ingestion-overview"

[[redirects]]
from = "/docs/first-database/"
to = "/docs/guides/create-database/"

[[redirects]]
from = "/docs/develop/query-data/"
to = "/docs/reference/sql/overview/"

[[redirects]]
from = "/docs/develop/update-data/"
to = "/docs/reference/sql/overview/"

[[redirects]]
from = "/docs/develop/authenticate"
to = "/docs/reference/api/ilp/authenticate/"

[[redirects]]
from = "/docs/reference/client/grafana"
to = "/docs/third-party-tools/grafana/"

[[redirects]]
from = "/docs/guides/aws-official-ami"
to = "/docs/deployment/aws-official-ami/"

[[redirects]]
from = "/docs/guides/digitalocean"
to = "/docs/deployment/digitalocean/"

[[redirects]]
from = "/docs/guides/google-cloud-platform"
to = "/docs/deployment/google-cloud-platform/"

[[redirects]]
from = "/docs/guides/kubernetes"
to = "/docs/deployment/kubernetes/"

[[redirects]]
from = "/blog/2020/12/10/building-a-garbage-free-network-stack-for-kafka-streams"
to = "/blog/2020/12/10/garbage-free-stack-for-kafka-streams/"

[[redirects]]
from = "/blog/2020/12/10/non-blocking-io-without-garbage-collection"
to = "/blog/2020/12/10/garbage-free-stack-for-kafka-streams/"

[[redirects]]
from = "/blog/2020/12/10/building-a-garbage-free-network-stack-for-kafka-streams"
to = "/blog/2020/12/10/non-blocking-io-without-garbage-collection/"

[[redirects]]
from = "/tutorial/2020/10/19/grafana/"
to = "/blog/time-series-monitoring-dashboard-grafana-questdb/"

[[redirects]]
from = "/blog/2020/10/19/grafana-tutorial/"
to = "/blog/time-series-monitoring-dashboard-grafana-questdb/"

[[redirects]]
from = "/tutorial/2020/06/05/iot-on-questdb"
to = "/blog/2020/06/05/iot-on-questdb/"

[[redirects]]
from = "/tutorial/2020/06/15/python-questdb-tutorial"
to = "/blog/exploring-financial-tick-data-jupyter-notebook-pandas/"

[[redirects]]
from = "/tutorial/2020/08/25/questitto"
to = "/blog/2020/08/25/fast-iot-stack-with-questdb-mqtt/"

[[redirects]]
from = "/blog/2020/11/26/http-server-contribution"
to = "/blog/2020/11/16/http-server-contribution/"

[[redirects]]
from = "/blog/2020/11/16/why-timeseries-data"
to = "/blog/2020/11/26/why-timeseries-data/"

[[redirects]]
from = "/blog/2020/03/15/interthread"
to = "/blog/2021/11/03/interthread/"

[[redirects]]
from = "/tutorial/2021/01/13/application-uptime-monitoring-with-python-nuxtjs-questdb"
to = "/blog/2021/01/13/application-uptime-monitoring-with-python-nuxtjs-questdb/"

[[redirects]]
from = "/tutorial/2021/01/18/low-code-bitcoin-ticker-workflow-with-time-series-database"
to = "/blog/2021/01/18/low-code-bitcoin-ticker-workflow-with-time-series-database/"

[[redirects]]
from = "/tutorial/2021/02/05/streaming-heart-rate-data-with-iot-core-and-questdb"
to = "/blog/2021/02/05/streaming-heart-rate-data-with-iot-core-and-questdb/"

[[redirects]]
from = "/tutorial/2021/02/18/realtime-crypto-tracker-with-kafka-and-questdb"
to = "/blog/2021/02/18/realtime-crypto-tracker-with-kafka-and-questdb/"

[[redirects]]
from = "/tutorial/2021/03/09/realtime-stock-alerts-python-grafana-questdb"
to = "/blog/2021/03/09/realtime-stock-alerts-python-grafana-questdb/"

[[redirects]]
from = "/tutorial/2021/03/18/questdb-and-prometheus-on-gke-autopilot"
to = "/blog/2021/03/18/questdb-and-prometheus-on-gke-autopilot/"

[[redirects]]
from = "/tutorial/2021/03/31/automating-etl-jobs-on-time-series-data-on-gcp"
to = "/blog/2021/03/31/automating-etl-jobs-on-time-series-data-on-gcp/"

[[redirects]]
from = "/tutorial/2021/04/12/ethereum"
to = "/blog/2021/04/12/stream-ethereum-data/"

[[redirects]]
from = "/tutorial/2021/06/18/tracking-multiple-cryptocurrency-exchanges"
to = "/blog/2021/06/18/tracking-multiple-cryptocurrency-exchanges/"

[[redirects]]
from = "/tutorial/2021/07/09/telegraf-and-questdb-for-storing-metrics-in-a-timeseries-database"
to = "/blog/2021/07/09/telegraf-and-questdb-for-storing-metrics-in-a-timeseries-database/"

[[redirects]]
from = "/tutorial/2021/07/05/comparing-questdb-timescaledb-influxdb/"
to = "/blog/comparing-influxdb-timescaledb-questdb-time-series-databases"

[[redirects]]
from = "/blog/2021/07/05/comparing-questdb-timescaledb-influxdb/"
to = "/blog/comparing-influxdb-timescaledb-questdb-time-series-databases"

[[redirects]]
from = "/tutorial/2021/08/18/questdb-versus-timescaledb"
to = "/blog/2021/08/18/questdb-versus-timescaledb/"

[[redirects]]
from = "/tutorial/2021/09/17/high-frequency-finance-julia-lang"
to = "/blog/2021/09/17/high-frequency-finance-julia-lang/"

[[redirects]]
from = "/tutorial/2021/11/01/plotly-finnhub-realtime-dashboard"
to = "/blog/2021/11/01/plotly-finnhub-realtime-dashboard/"

[[redirects]]
from = "/tutorial/2021/11/29/questdb-versus-influxdb"
to = "/blog/2024/02/26/questdb-versus-influxdb/"

[[redirects]]
from = "/tutorial/2021/11/22/high-frequency-finance-introduction-julia-lang"
to = "/blog/analyzing-financial-time-series-data-julia-language-questdb/"

[[redirects]]
from = "/blog/2021/11/22/high-frequency-finance-introduction-julia-lang/"
to = "/blog/analyzing-financial-time-series-data-julia-language-questdb/"

[[redirects]]
from = "/tutorial/2022/02/10/questdb-google-data-studio/"
to = "/blog/exploring-financial-tick-data-jupyter-notebook-pandas/"

[[redirects]]
from = "/tutorial/2022/03/08/questdb-crypto-pandas/"
to = "/blog/exploring-financial-tick-data-jupyter-notebook-pandas/"

[[redirects]]
from = "/tutorial/2022/03/14/mock-sql-timeseries-data-questdb/"
to = "/blog/2022/03/14/mock-sql-timeseries-data-questdb/"

[[redirects]]
from = "/tutorial/2022/03/15/cryptocurrency-grafana-questdb/"
to = "/blog/crypto-data-visualization-dashboards-grafana/"

[[redirects]]
from = "/blog/2022/03/15/cryptocurrency-grafana-questdb/"
to = "/blog/crypto-data-visualization-dashboards-grafana/"

[[redirects]]
from = "/tutorial/2022/03/29/crypto-volumes-julia-questdb/"
to = "/blog/2022/03/29/crypto-volumes-julia-questdb/"

[[redirects]]
from = "/docs/reference/client/cli"
to = "/docs/reference/command-line-options/"

[[redirects]]
from = "/docs/reference/client/web-console"
to = "/docs/reference/web-console/"

[[redirects]]
from = "/docs/guides/out-of-order-commit-lag/"
to = "/blog/2022/11/25/questdb-6.6.1-dynamic-commits/#questdbs-data-structure-and-out-of-order-data-ingestion"

[[redirects]]
from = "/tutorial/2021/09/05/telegraf-and-questdb-for-storing-metrics-in-a-timeseries-database"
to = "/blog/2021/07/09/telegraf-and-questdb-for-storing-metrics-in-a-timeseries-database/"

[[redirects]]
from = "/blog/2021/09/13/release-6-0-5"
to = "/blog/2021/09/13/release-6-0-5-geospatial-data/"

[[redirects]]
from = "/blog/2021/07/16/release-6-0-4"
to = "/blog/2021/07/16/release-6-0-4-prometheus-metrics/"

[[redirects]]
from = "/careers/head-of-talent/"
to = "/careers/people-and-talent-acquisition/"

[[redirects]]
from = "/careers/backend-software-engineer/"
to = "/careers/core-database-engineer/"

[[redirects]]
from = "/case-study/innova/"
to = "/case-study/turk-telekom/"

[[redirects]]
from = "/case-study/turk-telekom/"
to = "/"

[[redirects]]
from = "/developer-in-test"
to = "/careers/"

[[redirects]]
from = "/people-and-talent-acquisition"
to = "/careers/"

[[redirects]]
from = "/careers/senior-frontend-engineer/"
to = "/careers/"

[[redirects]]
from = "/docs/reference/sql/latest-by"
to = "/docs/reference/sql/latest-on/"

[[redirects]]
from = "/docs/reference/api/influxdb"
to = "/docs/reference/api/ilp/overview/"

[[redirects]]
from = "/docs/guides/influxdb-line-protocol"
to = "/docs/reference/api/ilp/overview/"

[[redirects]]
from = "/docs/faq/troubleshooting"
to = "/docs/troubleshooting/faq/"

[[redirects]]
from = "/blog/2022/05/26/multi-threaded-sql-filters"
to = "/blog/2022/05/26/query-benchmark-questdb-versus-clickhouse-timescale/"

[[redirects]]
from = "/docs/guides/aws-packer"
to = "/docs/deployment/aws-official-ami/"

[[redirects]]
from = "/docs/operations/deployment"
to = "/docs/deployment/aws-official-ami/"

[[redirects]]
from = "/docs/introduction"
to = "/docs/"

[[redirects]]
from = "/blog/2022/04/12/query-live-crypto-trades-with-sql-in-real-time"
to = "/blog/2022/04/12/demo-live-crypto-data-streamed-with-questdb-and-grafana/"

[[redirects]]
from = "/docs/reference/ilp-client-libraries"
to = "/docs/ingestion-overview/#first-party-clients"

[[redirects]]
from = "/docs/clients/overview"
to = "/docs/ingestion-overview/#first-party-clients"

[[redirects]]
from = "/tutorial"
to = "/blog/?tag=tutorial"

[[redirects]]
from = "/blog/2022/09/12/importing-3m-rows-with-io-uring"
to = "/blog/2022/09/12/importing-300k-rows-with-io-uring/"

[[redirects]]
from = "/docs/reference/sql/except-intersect"
to = "/docs/reference/sql/union-except-intersect/"

[[redirects]]
from = "/docs/reference/sql/timestamp"
to = "/docs/reference/function/timestamp/"

[[redirects]]
from = "/docs/third-party-tools/kafka/overview/"
to = "/docs/third-party-tools/kafka/"

[[redirects]]
from = "/docs/third-party-tools/kafka/questdb-kafka/"
to = "/docs/third-party-tools/kafka/#questdb-kafka-connect-connector"

[[redirects]]
from = "/docs/third-party-tools/kafka/jdbc"
to = "/docs/third-party-tools/kafka/"

[[redirects]]
from = "/blog/laoding-pandas-dataframes/"
to = "/blog/loading-pandas-dataframes/"


[[redirects]]
from = "/blog/2020/07/22/influxdb-lp-on-tcp/"
to = "/docs/ingestion-overview/#first-party-clients"

[[redirects]]
from = "/blog/2020/07/22/influxdb-lp-on-tcp/"
to = "/docs/ingestion-overview/#first-party-clients"

[[redirects]]
from = "/blog/how-reliable-your-distributed-database/"
to = "/blog/inner-workings-distributed-databases/"

[[redirects]]
from = "/blog/sql-performance-tuning-introducing-explain/"
to = "/blog/explain-sql-query-plan/"

[[redirects]]
from = "/blog/2021/02/18/realtime-crypto-tracker-with-kafka-and-questdb/"
to = "/blog/realtime-crypto-tracker-with-questdb-kafka-connector/"

[[redirects]]
from = "/blog/2022/06/07/data-pipeline-with-kafka-and-questdb/"
to = "/blog/processing-time-series-with-questdb-apache-kafka/"

[[redirects]]
from = "/blog/2021/06/18/tracking-multiple-cryptocurrency-exchanges/"
to = "/blog/ingesting-financial-tick-data-using-time-series-database/"

[[redirects]]
from = "/blog/ingesting-market-data-crypto-exchanges-using-time-series-database/"
to = "/blog/ingesting-financial-tick-data-using-time-series-database/"

[[redirects]]
from = "/blog/2019/12/19/lineprot/"
to = "/blog/"

[[redirects]]
from = "/blog/2022/08/22/using-birch-anomaly-detection-questdb/"
to = "/blog/"

[[redirects]]
from = "/blog/data-integration-strategies-for-tsdb/"
to = "/blog/data-integration-time-series-etl-elt-cdc/"

[[redirects]]
from = "/blog/2020/07/24/use-questdb-for-swag/"
to = "/community/"

[[redirects]]
from = "/blog/2022/03/08/questdb-crypto-pandas/"
to = "/blog/exploring-financial-tick-data-jupyter-notebook-pandas/"

[[redirects]]
from = "/blog/2022/02/10/questdb-google-data-studio/"
to = "/blog/exploring-financial-tick-data-jupyter-notebook-pandas/"

[[redirects]]
from = "/blog/2020/06/15/python-questdb-tutorial/"
to = "/blog/exploring-financial-tick-data-jupyter-notebook-pandas/"

[[redirects]]
from = "/docs/operations/capacity-planning/"
to = "/docs/deployment/capacity-planning/"

[[redirects]]
from = "/blog/visualizing-iot-data-questdb/"
to = "/blog/visualizing-iot-data-mqtt-questdb-grafana/"

[[redirects]]
from = "/docs/operations/health-monitoring/"
to = "/docs/operations/logging-metrics/"

[[redirects]]
from = "/docs/reference/logging/"
to = "/docs/operations/logging-metrics/"

[[redirect]]
from = "/docs/reference/function/ipv4/"
to = "/docs/reference/operators/ipv4/"

[[redirects]]
from = "/docs/reference/configuration/"
to = "/docs/configuration"

[[redirects]]
from = "/docs/concept/storagemodel/"
to = "/docs/concept/storage-model/"

[[redirects]]
from = "/docs/third-party-tools/"
to = "/docs/third-party-tools/overview/"

[[redirects]]
from = "/docs/get-started/binaries/"
to = "/docs/quick-start/"

[[redirects]]
from = "/docs/get-started/first-database/"
to = "/docs/quick-start/"

[[redirects]]
from = "/docs/get-started/docker/"
to = "/docs/quick-start/"

[[redirects]]
from = "/docs/get-started/docker/"
to = "/docs/quick-start/"

[[redirects]]
from = "/docs/guides/import-data/"
to = "/docs/guides/import-csv/"

[[redirects]]
from = "/docs/guides/importing-data-rest/"
to = "/docs/guides/import-csv/"

[[redirects]]
from = "/compare/influxdb-cloud/"
to = "/compare/influxdb/"

[[redirects]]
from = "/compare/influxdb-enterprise/"
to = "/compare/influxdb/"

[[redirects]]
from = "/blog/2020/11/26/why-timeseries-data/"
to = "/"

[[redirects]]
from = "/blog/time-series-data/"
to = "/"

[[redirects]]
from = "/blog/is-all-data-time-series-data/"
to = "/blog/what-is-time-series-data/"

[[redirects]]
from = "/docs/develop/insert-data/"
to = "/docs/ingestion-overview/"


[[redirects]]
from = "/blog/questdb-release-6-4"
to = "/"
status = 301
force = true

[[redirects]]
from = "/blog/cloud-getting-started"
to = "/"
status = 301
force = true


[[redirects]]
from = "/glossary/time-series/database/"
to = "/glossary/time-series-database/"
status = 301
force = true

[[redirects]]
from = "/blog/questdb-cloud-infrastructure"
to = "/"
status = 301
force = true

[[redirects]]
from = "/blog/release-week-4"
to = "/"
status = 301
force = true

[[redirects]]
from = "/cloud/"
to = "/enterprise/"
status = 301
force = true

[[redirects]]
from = "/get-questdb/"
to = "/"
status = 301
force = true

[[redirects]]
from = "/pricing/"
to = "/enterprise/"
status = 301
force = true

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "0"
X-Content-Type-Options = "nosniff"
Content-Security-Policy = "frame-src 'self' app.netlify.com *.demo.questdb.com *.questdb.com www.youtube.com www.slideshare.net forms.hsforms.com;"

[[headers]]
for = "/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
